### ISSUE TITLE
Error on docker

### ISSUE THREAD

**Issue by diegolisboajj** [omar0z/GlobomanticsInventoryApp#1]
here i gotted

Unable to find image 'globomantics:latest' locally
docker: Error response from daemon: pull access denied for globomantics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

i run docker login and the same thing

**Comment by omar0z** [comment]
Hello Diego!

Thanks for raising this up!.

The error is due to the line endings of the start and stop scripts. 

In the bottom-right corner of your VS Code window you should be seeing the following: 
![image](https://github.com/omar0z/GlobomanticsInventoryApp/assets/2214957/128bec81-8b1c-43c2-8dd0-22bcbda9c9e4)

If the line separator is set as "CRLF" (Windows style) , the script will throw the error you describe.  Click on the line separator, and on the pop-up menu, select "LF".  
![image](https://github.com/omar0z/GlobomanticsInventoryApp/assets/2214957/bfac3e0f-b0d2-46a1-a176-b2580abbfe98)

Once the line separator is set to "LF", you can go ahead and try to run the script again. Things should be running as expected :) 

Let me know if that solves your issue! 

Cheers, 

Omar.
